name: build

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dev requirements
      run: pip install flake8 safety pytest

    - name: Valide Flake8
      run: flake8 .
    - name: validade security
      run: safety check -r requirements.txt

    - name: validade test
      run: python -m pytest tests
